-- blog_posts never had a migration in this repo at all (same class of gap as
-- watchlist/portfolios/ai_conversations found earlier) -- src/lib/blog.functions.ts
-- has queried it all along with nothing here to create it. Public read (it's a
-- public blog), write restricted to the single owner identity already used to
-- gate blog authoring client-side (src/lib/admin.ts) and community moderation
-- (20260726090000_update-admin-email.sql) -- same email, so this is real
-- server-side enforcement, not just a client-side UI gate.
CREATE TABLE IF NOT EXISTS public.blog_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  content TEXT NOT NULL,
  source_name TEXT,
  source_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.blog_posts TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.blog_posts TO authenticated;
GRANT ALL ON public.blog_posts TO service_role;
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "blog posts public read" ON public.blog_posts;
CREATE POLICY "blog posts public read" ON public.blog_posts FOR SELECT USING (true);
DROP POLICY IF EXISTS "blog posts owner insert" ON public.blog_posts;
CREATE POLICY "blog posts owner insert" ON public.blog_posts FOR INSERT WITH CHECK ((auth.jwt() ->> 'email') = 'admin@s-markets.com');
DROP POLICY IF EXISTS "blog posts owner update" ON public.blog_posts;
CREATE POLICY "blog posts owner update" ON public.blog_posts FOR UPDATE USING ((auth.jwt() ->> 'email') = 'admin@s-markets.com');
DROP POLICY IF EXISTS "blog posts owner delete" ON public.blog_posts;
CREATE POLICY "blog posts owner delete" ON public.blog_posts FOR DELETE USING ((auth.jwt() ->> 'email') = 'admin@s-markets.com');

-- Initial seed: 6 original educational articles, expanded from the Learn
-- path's Group 1 lessons (see 20260802100000_add-learn-lessons.sql) plus 3
-- original pieces on other real, shipped analytics concepts (Sharpe ratio,
-- asset allocation, diversification/concentration) -- never on backtesting,
-- which was removed from the app earlier and isn't a current feature. Slugs
-- are clean and human-readable (not the app's own random-suffixed slugify)
-- since these are inserted directly, and readable slugs are better for SEO
-- anyway. Guarded by "table is empty" so this only ever seeds once.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.blog_posts) THEN
    INSERT INTO public.blog_posts (slug, title, excerpt, content, created_at) VALUES
      ('what-is-an-emergency-fund-and-why-it-comes-before-investing', 'What Is an Emergency Fund and Why It Comes Before Investing', 'Why most financial educators say to build a cash safety net before you invest a single dollar — and what can go wrong if you skip it.', 'Before putting a single dollar into the market, most financial educators recommend building something less exciting but arguably more important: an emergency fund. It''s not an investment. It won''t grow your wealth. Its entire job is to sit quietly in an easily accessible account and be there the one time you really need it.

The logic behind this ordering is worth understanding, because it''s not just conventional wisdom — it''s a direct response to how investment risk and personal financial emergencies tend to collide at the worst possible moment.

Here''s the scenario an emergency fund is designed to prevent. You''ve invested money in a diversified portfolio. The market experiences a downturn — nothing unusual, this happens regularly and is a normal part of investing over any long time horizon. At the same time, something in your life goes wrong: a job loss, a medical bill, an urgent home or car repair. If the only money you have access to is invested, you''re forced to sell during the downturn, at a lower price than you bought, to cover an expense that has nothing to do with your investment strategy. You''ve converted what should have been a temporary paper loss into a locked-in real one, at the exact moment you had no choice in the timing.

An emergency fund breaks this chain. By keeping several months of essential expenses in a separate, stable, liquid account — not invested, not exposed to market swings — a genuine emergency stops being a reason to touch your portfolio at all. The market can do whatever it does, and your investment strategy doesn''t need to change because your water heater broke.

How much is enough is genuinely personal, and reasonable educators disagree on the exact number — some talk about three months of expenses, others six, and the right answer depends on things like job stability, whether you have dependents, and how predictable your income is. What matters more than the precise figure is the principle: this money exists for one purpose (unplanned necessity), lives somewhere boring and accessible (not the market), and is treated as separate and off-limits from your investment plan.

It''s worth being clear about what an emergency fund is not. It''s not a place to grow wealth — that''s what investments are for, and holding too much cash for too long comes with its own cost, since inflation erodes purchasing power sitting in cash over time. It''s also not a wishlist fund or a vacation fund; blending "emergency" money with "want to spend eventually" money defeats the purpose, because now there''s ambiguity about whether it''s really available when an actual emergency hits.

There''s also a psychological dimension that''s easy to underestimate. Investors without an emergency cushion tend to feel every market downturn more acutely, because a downturn isn''t just an abstract number on a screen — it''s a real threat to their ability to handle whatever life throws at them next. That anxiety often leads to exactly the kind of reactive, poorly-timed decisions — panic-selling during a dip, for instance — that tend to hurt long-term returns the most. An emergency fund, in that sense, isn''t just a financial safety net; it''s also what lets an investor stay calm and stick with a long-term plan through short-term volatility.

None of this is a reason to delay investing indefinitely while you build up cash — for many people, building even a modest emergency fund in parallel with starting to invest small amounts is a completely reasonable approach, and there''s no universal rule that says you must hit some specific cash target before you''re "allowed" to invest a dollar. The point isn''t sequencing perfection; it''s making sure that whenever you do invest, it''s money you can genuinely afford to leave alone through short-term ups and downs — because that''s the only way compounding, diversification, and the rest of the tools available to an investor actually get the chance to work as intended.

This article is educational and general in nature. It is not personalized financial advice, and how much of an emergency fund makes sense for your situation depends on facts about your own finances that only you (or a licensed financial advisor) can properly weigh.', '2026-07-20T09:00:00Z'),
      ('saving-vs-investing-whats-the-real-difference', 'Saving vs Investing: What''s the Real Difference', 'Saving and investing get used interchangeably, but they serve different jobs — here''s the difference that actually matters.', 'The words "saving" and "investing" get used almost interchangeably in everyday conversation, but they describe two genuinely different activities, with different goals, different tools, and different amounts of risk. Understanding the distinction is one of the more useful mental models in personal finance, because a lot of confusion and poor decisions come from applying "saving" logic to money that should be invested, or vice versa.

Saving, in the strict sense, means setting money aside somewhere safe and easily accessible — typically a bank account. The defining feature of savings is that the amount is stable and predictable. If you put a hundred dollars in a savings account, you can be confident that money will still be there, and roughly that same value, when you go to withdraw it. The tradeoff for that stability is that savings generally grow slowly, if at all, and often don''t keep pace with inflation over long periods.

Investing means using money to acquire assets — stocks, bonds, real estate, funds, and similar instruments — with the expectation that their value can grow over time. The critical difference from saving is that this value is not fixed or guaranteed. An investment''s worth can rise, and it can also fall, sometimes significantly, especially over short time periods. That volatility is the price of admission for the higher long-term growth potential that investing offers over saving.

Neither approach is inherently "better" — they''re suited to different jobs. Money that you might need in the next weeks, months, or, for most people, in the next few years, is generally better off saved rather than invested, precisely because you don''t want to be forced to sell an investment at a bad time just because you needed the cash on a fixed schedule. Money that you have a genuinely long time horizon for — years, ideally longer — is where investing''s growth potential has the most room to play out, and where its short-term ups and downs matter less, because you''re not planning to touch that money soon anyway.

A simple way many people frame this: save for what you need soon or can''t afford to lose; invest what you can leave alone for years. This isn''t a rigid formula, and real financial lives are messier than any two-bucket system, but it''s a genuinely useful starting lens.

It''s also worth noting that "safe" and "risk-free" aren''t quite the same thing, even for savings. Cash sitting in a low- or no-interest account is still exposed to a slower, quieter risk: inflation. Over enough time, the same dollar amount buys less than it used to, even though the number in the account hasn''t changed. This is one of the reasons investing exists as a concept at all — for money with a long enough time horizon, taking on some volatility in exchange for growth that can outpace inflation is often considered, by many educators, a reasonable trade.

The mistake worth avoiding in either direction is treating investment money like savings, or savings money like an investment. Panicking and selling an investment during a temporary downturn, as if it were supposed to behave like a stable savings account, often locks in a loss that would have recovered given more time. On the other end, leaving money that you''ll need soon in a volatile investment, hoping for extra growth, risks it not being there — or not being there in the amount you need — exactly when you need it.

Figuring out where a specific dollar of your own money belongs — saved or invested, and in what — depends on your own goals, timeline, and risk tolerance, and is a question worth discussing with a licensed financial advisor if you want guidance specific to your situation. This article is educational and general, not a personalized recommendation.', '2026-07-23T09:00:00Z'),
      ('why-starting-to-invest-early-matters-more-than-how-much-you-start-with', 'Why Starting to Invest Early Matters More Than How Much You Start With', 'The math behind why an early start tends to matter more than a large one — and the common trap that gets in the way.', 'One of the more counterintuitive ideas in investing is that when you start often matters more than how much you start with. It sounds almost too simple to be useful advice, but the mathematics behind it — compounding — is genuinely one of the most powerful forces available to any investor, and it rewards time in a way that''s very hard to make up for later.

Compounding is the process by which investment growth itself starts generating its own growth. If an investment grows in value, that new, larger amount is now what''s being invested going forward — so future growth is calculated on a bigger base than before. Over short periods this effect is barely noticeable. Over long periods, it can be dramatic, because growth is being layered on top of growth, again and again, like a snowball picking up more snow as it rolls.

The reason time matters so much is that compounding needs time to do its work. Each additional year an investment has to grow is another layer added to that snowball. Two people who invest the exact same total amount of money over their lives, but at different starting ages, can end up with very different outcomes — not because one of them was smarter or picked better investments, but purely because one gave their money more years to compound.

This is where the common trap comes in: "I''ll start investing seriously once I have more money to put in." It''s an understandable instinct — putting in a small amount can feel almost not worth doing, especially compared to some larger sum you imagine having later. But this reasoning quietly ignores the cost of the years lost waiting. A modest amount invested early, given enough time to compound, has in many illustrative scenarios outperformed a larger amount invested later, simply because it had more time working in its favor.

None of this means timing markets perfectly, or that starting immediately with an enormous amount is the right move for everyone — it isn''t, and how much anyone should invest depends on their own financial circumstances, including whether they have higher-priority needs like an emergency fund or high-interest debt to address first. The point is narrower and more specific: all else being equal, time in the market — meaning the number of years an investment is allowed to sit and compound — tends to matter more than trying to perfectly optimize the amount or the entry price.

It''s also worth being honest about what compounding doesn''t promise. It''s not a guarantee of a specific outcome, and markets don''t move in a smooth, predictable upward line — there are periods of decline along the way, sometimes lasting years. The "more time equals more compounding" idea works as a long-term statistical tendency across market history, not as a promise about any particular stretch of time or any particular investment.

The practical takeaway that most educators land on isn''t "invest everything immediately regardless of your situation" — it''s simply that delaying the start of investing has a real, often underappreciated cost, and that starting small, early, tends to beat waiting for an ideal moment or an ideal amount that may never quite arrive. What amount and timing actually makes sense for you depends on your own finances and goals, and this article is educational in nature, not a personalized recommendation to invest a specific amount at a specific time.', '2026-07-27T09:00:00Z'),
      ('what-is-the-sharpe-ratio-and-why-it-matters-more-than-returns-alone', 'What Is the Sharpe Ratio and Why It Matters More Than Returns Alone', 'Two portfolios can have identical returns and very different risk. Here''s the ratio that measures the difference.', 'When people compare investments or portfolios, the instinct is almost always to look at returns first: which one made more money over some period. It''s an intuitive starting point, but it''s also incomplete, because it ignores a question that matters just as much — how much risk was taken to get that return. This is exactly the gap the Sharpe ratio is designed to fill.

Developed by economist William Sharpe, the Sharpe ratio measures return relative to risk, rather than return in isolation. Specifically, it looks at how much return a portfolio produced above a "risk-free" baseline (traditionally something like a very short-term government bond, which is treated as close to zero-risk), and divides that by how volatile the portfolio''s returns were along the way. The result is a single number that answers a more useful question than raw returns alone: for the amount of risk taken, how much reward did that risk actually deliver?

Why does this distinction matter in practice? Consider two hypothetical portfolios that both returned, say, 10% over a year. On paper, comparing returns alone, they look identical. But if one of those portfolios took a wild, volatile path to get there — large swings up and down along the way — while the other rose in a comparatively smooth, steady line, most investors would reasonably prefer the smoother path, because it implies a similar outcome was achieved with meaningfully less risk of a bad surprise along the way. The Sharpe ratio is one of the standard tools for quantifying exactly that difference: a higher Sharpe ratio means more return was earned per unit of volatility endured; a lower one means the same return came with a bumpier, riskier ride.

This is why comparing two investments purely on their headline returns can be misleading. A portfolio that returned less overall but did so with dramatically lower volatility might actually represent a "better" risk-adjusted outcome than one that returned more but experienced much larger swings — depending on what an investor actually cares about and can tolerate.

It''s worth being precise about what the Sharpe ratio does and doesn''t tell you. It''s a backward-looking statistical measure calculated from historical returns and volatility — it describes how a portfolio has behaved, not a guarantee of how it will behave going forward. It also doesn''t distinguish between "good" volatility (sharp upward moves) and "bad" volatility (sharp downward moves) — it treats both as part of the same volatility measure, even though most investors would say a strong upside surprise doesn''t feel like the same kind of risk as a sharp downside one. Other metrics, like the Sortino ratio, were developed specifically to address that asymmetry by focusing only on downside volatility.

There''s also no single "good" Sharpe ratio number that applies universally — what counts as a strong risk-adjusted return varies by asset class, time period, and market conditions, and comparing Sharpe ratios is generally most meaningful when comparing similar types of portfolios over the same time period, rather than treating any single number as an absolute verdict.

Understanding the Sharpe ratio doesn''t tell you what to invest in — it''s a lens for evaluating risk-adjusted performance after the fact, useful for building intuition about how a given portfolio behaved, not a signal to buy, sell, or hold any specific investment. This article is educational and general; it isn''t personalized investment advice.', '2026-07-30T09:00:00Z'),
      ('what-is-asset-allocation-and-why-its-the-biggest-driver-of-portfolio-risk', 'What Is Asset Allocation and Why It''s the Biggest Driver of Portfolio Risk', 'The mix of stocks, bonds, and cash in a portfolio often drives its risk more than which individual holdings are chosen.', 'Ask ten people what makes a portfolio risky, and most will start talking about which specific stocks or funds are in it. That instinct isn''t wrong exactly, but it usually misses the bigger picture. A large and often underappreciated body of investment research points to something more structural as the dominant driver of a portfolio''s overall risk and return characteristics: asset allocation — the mix of broad asset categories a portfolio holds, like stocks, bonds, cash, real estate, or commodities, and in what proportions.

The core idea is that different asset classes behave differently, especially in how they respond to the same economic conditions. Stocks, as a category, have historically offered higher long-term growth potential but with more volatility along the way. Bonds have historically offered more stability and steadier income, generally with lower growth potential. Cash offers the most stability of all, with essentially no growth. Real estate and commodities each bring their own distinct behavior. A portfolio''s overall risk and return profile is shaped enormously by how much weight it gives to each of these categories, before you even get to the question of which specific stocks or bonds are chosen within each one.

This is why two portfolios can hold completely different individual stocks and end up with a very similar risk profile, if their overall stock-versus-bond-versus-cash mix is similar — and conversely, why two portfolios that happen to share several of the same individual stock positions can have very different overall risk if their broader asset mix differs. The forest, in this sense, tends to matter more than the individual trees.

Asset allocation decisions are typically framed around two things: time horizon and risk tolerance. Someone with a long time horizon ahead of them and the temperament to sit through volatility along the way has historically had more room to weight a portfolio toward higher-growth, higher-volatility assets like stocks, because there''s more time to recover from any downturns. Someone with a shorter time horizon, or who would react poorly to seeing their portfolio''s value swing significantly, has generally leaned toward including more of the steadier categories like bonds and cash, accepting lower long-term growth potential in exchange for a smoother ride.

There''s no single allocation percentage that''s correct for everyone, and that''s an important point, not a cop-out — the right mix genuinely depends on an individual''s specific goals, time horizon, other financial resources, and comfort with volatility, all of which vary enormously from person to person. Generic examples you''ll see in educational contexts, like a "60/40" stock-to-bond split, are illustrative reference points for discussing how allocation concepts work, not a personalized prescription that fits any particular investor.

It''s also worth noting that allocation isn''t a "set once and forget forever" decision. As markets move, a portfolio''s actual proportions drift away from wherever they started — if stocks perform particularly well, for instance, they naturally grow to represent a larger share of the total portfolio than originally intended, even without anyone taking any action. This drift is one of the main reasons the idea of periodically rebalancing — adjusting a portfolio back toward its intended mix — exists as a common practice in portfolio management.

Thinking in terms of allocation, rather than only individual holdings, is a genuinely useful shift in how to reason about portfolio risk. What allocation actually makes sense for you is a personal question shaped by your own circumstances, and this article is educational and general in nature — not a recommendation for any specific allocation.', '2026-08-01T09:00:00Z'),
      ('diversification-101-why-its-diversified-isnt-always-true', 'Diversification 101: Why "It''s Diversified" Isn''t Always True', 'A portfolio can hold twenty positions and still be a concentrated bet in disguise. Here''s what real diversification requires.', 'Diversification is one of the most repeated pieces of investing wisdom, and for good reason — spreading investments across different holdings genuinely does reduce the risk that any single bad outcome sinks an entire portfolio. But the word gets used loosely enough in everyday conversation that it''s worth being precise about what real diversification actually requires, because a portfolio that looks diversified on the surface can be far more concentrated than it appears.

The basic logic of diversification is straightforward: if a portfolio holds only one investment, its entire fate is tied to that one thing. If that single holding performs badly, the whole portfolio performs badly. Spread that same money across many different holdings, and a bad outcome in any one of them affects only a fraction of the total — assuming those holdings don''t all move in the same direction for the same reason at the same time.

That last condition is where things get more subtle than "own more than one thing." True diversification isn''t just about the number of holdings — it''s about how independently those holdings behave from each other, a concept usually discussed in terms of correlation. Owning twenty different companies sounds diversified, but if all twenty are in the same industry, operating in the same country, exposed to the same economic forces, they may still move together far more than most people would expect, especially during periods of market stress, when many historically-uncorrelated assets have a tendency to become more correlated all at once.

This is why measures of concentration matter alongside a simple holdings count. One useful lens is looking at how much of a portfolio''s value sits in its single largest position, or its largest sector, or its largest country exposure — regardless of how many total positions exist on paper. A portfolio with fifteen positions, twelve of which are large technology companies, is, in a meaningful sense, a concentrated technology bet dressed up as a diversified portfolio. The real exposure isn''t to fifteen independent stories — it''s largely to one story: how the technology sector performs.

Fund-based investing adds another layer worth understanding. A single fund — an ETF or mutual fund, for instance — can itself hold dozens or hundreds of underlying companies, and buying one share of that fund does provide real diversification across all of them. But it''s worth looking through to what a fund actually holds, rather than assuming any fund is automatically diversified just because it''s a fund; some funds are built around narrow themes or single sectors, and can be just as concentrated, in their own way, as owning a handful of individual stocks directly in that same space.

None of this means concentration is always a mistake — some investors deliberately choose more concentrated positions, accepting the added risk in pursuit of potentially higher reward, and that''s a legitimate approach for those who understand and accept the tradeoff. The point of understanding real diversification isn''t to declare concentration universally wrong; it''s to make sure that whatever level of concentration or diversification exists in a portfolio is there on purpose, understood clearly, rather than hidden behind a large-looking count of individual holdings that all happen to move together.

Evaluating how genuinely diversified a specific portfolio is, and whether its actual level of concentration fits a particular investor''s goals and risk tolerance, is a personal question that depends on individual circumstances. This article is educational and general in nature, and isn''t a personalized recommendation about how diversified any specific portfolio should be.', '2026-08-03T09:00:00Z');
  END IF;
END $$;
